# Web service configuration
web_service:
    # Port on which the web service will listen
    port: 8080

# Media paths configuration
# Each path has a name and a file system path
media_paths:
    movies:
        path: "/mnt/media/movies"
        description: "Main movie collection"

    tvshows:
        path: "/mnt/media/tvshows"
        description: "TV series collection"
